Repository VigneshDevHub/CampX, pull requests merged in 2024-10, with the labels that each got.

#41 Feature: Admin User Role for Enhanced Control
  README.md
  controllers/users.js
  middleware.js
  models/user.js
  views/campgrounds/show.ejs
Labels: enhancement, feature, hacktoberfest, hacktoberfest-accepted

#42 Merging from test to main
  README.md
  controllers/users.js
  middleware.js
  models/user.js
  public/stylesheets/home.css
  views/campgrounds/show.ejs
  views/home.ejs
Labels: hacktoberfest, hacktoberfest-accepted

#53 Merging changes from test to main
  .github/workflows/greeting.yml
Labels: hacktoberfest, hacktoberfest-accepted

#58 Merging changes from test to main
  controllers/campgrounds.js
  package.json
  routes/campgrounds.js
  views/campgrounds/index.ejs
Labels: hacktoberfest, hacktoberfest-accepted

#69 Merging changes from test to main
  .github/workflows/auto-label-issues.yml
  .github/workflows/labeler.yml
  .github/workflows/release.yml
Labels: hacktoberfest-accepted

#70 Update greeting.yml
  .github/workflows/greeting.yml
Labels: hacktoberfest, hacktoberfest-accepted

#71 Merging changes from test to main
  .github/workflows/greeting.yml
Labels: hacktoberfest, hacktoberfest-accepted

#83 Pushing changes due to turf in package-lock.json
  package-lock.json
Labels: hacktoberfest, hacktoberfest-accepted

#84 Merging changes from test to main
  package-lock.json
Labels: hacktoberfest, hacktoberfest-accepted

#87 Merging changes from test to main
  public/stylesheets/app.css
  views/campgrounds/show.ejs
Labels: hacktoberfest, hacktoberfest-accepted

#86 Add GitHub Action that automatically displays all contributors in the READMEContributor
  .github/workflows/update-contributors.yml
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level 2

#89 Merging changes from test to main
  .github/workflows/update-contributors.yml
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#108 [FEATURE] [ Fixes #77] Add search functionality in campgrounds
  controllers/campgrounds.js
  public/stylesheets/searchCampground.css
  routes/campgrounds.js
  views/campgrounds/index.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#129 [FEATURE] Add navigation button between login and Register page
  views/users/login.ejs
  views/users/register.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#138 Error div update
  app.js
  controllers/campgrounds.js
  middleware.js
  views/error.ejs
Labels: hacktoberfest-accepted

#139 webicon updated
  public/icons/logo-modified.png
Labels: hacktoberfest-accepted

#149 Add cron job: Implemented periodic HTTPS requests to keep the webapp active
  app.js
  cron.js
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level2

#137 [UI] Enhance navbar
  app.js
  public/stylesheets/navbar.css
  views/layouts/boilerplate.ejs
  views/partials/navbar.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#165 Fix the ISSUE #127 that is fix the review section
  public/icons/bin.png
  public/icons/outline.png
  public/icons/solid.png
  public/icons/user2.png
  public/javascripts/showPageMap.js
  public/stylesheets/app.css
  views/campgrounds/index.ejs
  views/campgrounds/show.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#175 Enhanced the login and signup page.
  views/users/login.ejs
  views/users/register.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#128 added scroll to top feature
  public/icons/arrow-upp.png
  public/icons/upload32.png
  public/stylesheets/app.css
  views/campgrounds/index.ejs
Labels: hacktoberfest-accepted

#170 Add [feature/fix]: [Fixed the Login UI by redesigning it]
  public/stylesheets/login.css
  views/layouts/boilerplate.ejs
  views/users/login.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#230 made UI changes on campground page
  public/stylesheets/searchCampground.css
  views/campgrounds/index.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#228 Redesigned Landing Page
  public/javascripts/backgroundChanger.js
  public/stylesheets/home.css
  views/home.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level3

#243 Changes for update map pointer in edit route ISSUE #155
  controllers/campgrounds.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#221 ISSUE #220 Updated campground.js in models
  models/campground.js
Labels: hacktoberfest-accepted

#240 Converted_Images_to_WebP_for_Better_Optimization
  public/icons/arrow-upp.png
  public/icons/arrow-upp.webp
  public/icons/bin.png
  public/icons/bin.webp
  public/icons/hidden.png
  public/icons/hidden.webp
  public/icons/logo-modified.png
  public/icons/logo-modified.webp
  public/icons/outline.png
  public/icons/outline.webp
  public/icons/solid.png
  public/icons/solid.webp
  public/icons/upload32.png
  public/icons/upload32.webp
  public/icons/user2.png
  public/icons/user2.webp
  public/icons/visible.png
  public/icons/visible.webp
  views/campgrounds/show.ejs
  views/users/login.ejs
  views/users/register.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#238 Enhanced navbar
  public/stylesheets/navbar.css
  views/partials/navbar.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#252 Improved the new campground page
  public/stylesheets/newCampground.css
  views/campgrounds/new.ejs
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#273 ISSUE #272 (solved) Enhance Code Documentation and Structure for Mapbox Integration
  public/javascripts/clusterMap.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#262 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr_validation.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#282 ISSUE #280 (solved) Improve Code Documentation for Middleware and Security Configurations
  app.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#279 Edit Campground Page improved
  public/stylesheets/editCampground.css
  views/campgrounds/edit.ejs
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#263 Enhanced the file
  CONTRIBUTING.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#291 ISSUE #290 (solved) Improved code readability and documentation
  controllers/campgrounds.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#297 ISSUE #296 (solved) Improved Documentation, Formatting, and Error Handling for Review Module
  controllers/reviews.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#305 Merging changes from test to main
  CONTRIBUTING.md
  README.md
  controllers/campgrounds.js
  controllers/reviews.js
Labels: documentation

#287 [FIX] Capmgrounds page resposiveness for mobile devices
  public/stylesheets/searchCampground.css
  views/campgrounds/index.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#313 Fix the problem of Review spamming || Also solve the conflict
  controllers/campgrounds.js
  controllers/reviews.js
  views/campgrounds/show.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level3

#310 Enhanced Footer with Social Links ON README
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#318 Flash message improvement ISSUE #242
  public/javascripts/flashMsg.js
  views/layouts/boilerplate.ejs
  views/partials/flash.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#322 Issue #321 solved improved code documentation
  views/home.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#324 issue #323 solved improved code and documentation
  views/error.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#312 Enhancing the contributor Section and Structuring
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#325 ISSUE #319 solved
  controllers/users.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#330 Successfully Updated CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#334 Add default avatar
  public/icons/profile.webp
  public/stylesheets/app.css
  views/campgrounds/show.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#332 Improve the BUG template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#333 Review section improvement
  views/campgrounds/show.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#339 Enhance the Documentation Template
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/documentation_issue.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#335 defined constant role variables and changed related files accordingly
  controllers/campgrounds.js
  controllers/users.js
  middleware.js
  models/user.js
  utils/constant.js
  views/campgrounds/show.ejs
Labels: hacktoberfest-accepted
