Repository VigneshDevHub/CampX, pull requests merged in 2024-11, with the labels that each got.

#194 Added the auto search on entering by user
  controllers/campgrounds.js
  views/campgrounds/index.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level3

#353 Enhance the Feature Template
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#355 CREATE A CUSTOM TEMPLATE
  .github/ISSUE_TEMPLATE/Custom.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#375 Updating Project Structure in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#388 Display Price on Individual Campground Listing Pages (#382)
  views/campgrounds/show.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#387 Display Price on All Campground Listing Cards (#381)
  views/campgrounds/index.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level1

#391 ADD Q&A Suggestion Template
  .github/ISSUE_TEMPLATE/config.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#359 Enhance Campground Page layout
  public/stylesheets/campgroundPage.css
  views/campgrounds/index.ejs
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#395 Fix index page for handeling long description and title field.
  controllers/campgrounds.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#398 Fixes done for large review.
  controllers/reviews.js
  public/stylesheets/app.css
  views/campgrounds/show.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#401 Implemented forgot password functionality
  .sample.env
  app.js
  controllers/users.js
  models/user.js
  package-lock.json
  package.json
  public/stylesheets/login.css
  routes/users.js
  views/users/login.ejs
  views/users/resetpassword.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level3

#404 ADD UI Issue Report Template
  .github/ISSUE_TEMPLATE/UI_issue.yml
  .github/ISSUE_TEMPLATE/ui-change-issue-template.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#405 resolved reviews overflow bug
  public/stylesheets/review.css
  views/campgrounds/show.ejs
Labels: gssoc-ext, hacktoberfest-accepted, level2

#406 Merging changes from test to main
  .github/ISSUE_TEMPLATE/UI_issue.yml
  .github/ISSUE_TEMPLATE/ui-change-issue-template.md
  public/stylesheets/review.css
  views/campgrounds/show.ejs
Labels: ui
